### ISSUE TITLE
Can't compile owl-zoo: undefined symbol std::cout

### ISSUE THREAD

**Issue by tenomoto** [owlbarn/owl#435] opened 2019-08-17 06:35 UTC
I have `owl` installed but not `owl-top` because of `owl-zoo` on FreeBSD.

`owl-zoo` fails to find stdc++, which is referenced from `libeigen_cpp_stubs.a`.

I tried building and installing `eigen` and exporting `OWL_LDFLAGS="-L/usr/local/lib -L/usr/local/lib/gcc9 -lstdc++`.

**Comment by tenomoto** [comment] 2019-08-17 06:45
I can, however, run Jupyter examples with minor modification without `owl-top`.

```:sinc.ml
#require "owl, jupyter.notebook";; (* owl instead of owl-top *)

open Owl;;
open Owl_plplot;; (* added *)

let f x = Maths.sin x /. x in
let h = Plot.create "plot_003.png" in
Plot.set_foreground_color h 0 0 0;
Plot.set_background_color h 255 255 255;
Plot.set_title h "Function: f(x) = sine x / x";
Plot.set_xlabel h "x-axis";
Plot.set_ylabel h "y-axis";
Plot.set_font_size h 8.;
Plot.set_pen_size h 3.;
Plot.plot_fun ~h f 1. 15.;
Plot.output h;;

(* Load into memory and display in Jupyter *)

Jupyter_notebook.display_file ~base64:true "image/png" "plot_003.png"
```

**Comment by mseri** [comment] 2019-08-17 07:22
Sorry to hear that. Problems with eigen (github.com/owlbarn/eigen) are trickier to solve. You can try manually adding the flags in the various dune files: probably https://github.com/owlbarn/eigen/blob/master/eigen/dune and https://github.com/owlbarn/eigen/blob/master/eigen_cpp/lib/Makefile should be enough.

We are planning to get rid of eigen and reimplement sparse matrices differently, but it is going to take some times due to lack of work force 😔

**Comment by mseri** [comment] 2019-08-17 07:25
I was looking at the code, we can probably ease things up by making `owl-top` completely independent from the zoo. It is quite a simple change, I’ll try to send a PR soon next week

**Comment by jzstark** [comment] 2019-08-17 08:36
A similar issue is here: #430. It's not really caused `owl-zoo` but the lower level implementation of Eigen as Marcello pointed out. Fixing the code structure could be helpful to reveal the true source of error. In the end we plan to remove the dependency on Eigen.

**Comment by ryanrhymes** [comment] 2019-08-18 07:30
There were multiple similar issues before (caused by Eigen), and I commented before that "I am not particularly happy with Eigen ...". In the long run, Eigen will be replaced by something else, Google already switch to MKL from Eigen in TF (@jzstark am I right?).

I am wondering how many people are actually using sparse structure in Owl, maybe we shall consider to split sparse part out as a seprate sub-lib, so that the Owl core part can get rid of Eigen dependency to avoid similiar issues for the time being?

**Comment by ryanrhymes** [comment] 2019-08-18 07:33
I will try to allocate more time in looking into other candidates to estimate how long it might take to incorporate a new sparse lib, then discuss with owl team to decide what would be best strategy to avoid similar issues.

**Comment by jzstark** [comment] 2019-08-18 12:51
Yes indeed, currently TensorFlow has already widely adopted MKL-backend version in its recent CPU distributions. MKL is also used in rencet NumPy and Julia etc. Despite the lots of issues that using Eigen has caused, I would say that moving away from Eigen is the trend.

**Comment by ryanrhymes** [comment] 2019-12-04 12:07
@jzstark is this still relevant or can we actually solve this in owl itself ... shall this be moved to eigen ... can we close this?

**Comment by jzstark** [comment] 2019-12-04 12:51
I think we can close this issue in Owl, or at least move this issue to eigen since this problem is caused by installing eigen in certain environments. It's not likely we could replace Eigen very soon.

**Closed** 2019-12-04 13:25 UTC
Labels: bug, enhancement
