### ISSUE TITLE
Neural.S.Graph.save does not work

### ISSUE THREAD

**Issue by clecat** [owlbarn/owl#425] opened 2019-07-05 11:57 UTC
I am trying to save a neural network in order to keep my training between my executions.
But when I try to use `Neural.S.Graph.save` I get this error:
```
Invalid_argument("output_value: functional value")
```
It is due to [marshal_to_file](https://github.com/owlbarn/owl/blob/master/src/base/misc/owl_io.ml#L113) blindly calling Marshal.to_channel with an empty list of flags:
Indeed, as a neural network contains functions, we need to give marshal the argument `Marshal.Closures`.

Changing marshal_to_file so it accepts an optional list of flags could solve the issue (and therefore change the needed calls with the good  flags):
```
let marshal_to_file ?(flags=[]) x f =
  let h = open_out f in
  Marshal.to_channel h x flags;
  close_out h
```

**Comment by clecat** [comment] 2019-07-05 12:00
i didn't pay enough attention sorry, but it was mentioned [there](https://github.com/owlbarn/owl/issues/92) too

**Comment by jzstark** [comment] 2019-07-05 12:05
Yes it's caused by the lambda layer. It would be great if there is a way to marshal functions, but one current solution is to save weights instead of the whole network.

**Comment by clecat** [comment] 2019-07-05 12:19
I see, I'll try that. Actually `Marshal.Closures` allows that, I'm just unable to use my neural network if I modify my program.

**Comment by mseri** [comment] 2019-07-05 21:45
One thing we could allow, although I don’t know if the benefits outweigh the risks, is to allow saving the closures via flag, maybe adding an `~unsafe: bool` to the save function and showing a warning message if unsafe+functions are used while keeping the same (default) behavior with unsafe set to false

**Comment by ryanrhymes** [comment] 2019-07-15 07:58
@mseri that is a good solution. @jzstark can you add this option? You probably need to modify the save function, which fires a warning when it detects Lambda neuron is contained in the graph.

**Comment by jzstark** [comment] 2019-07-15 09:24
Cool, this would solve the issue in saving network with lambda layer. I'll add this function today or tomorrow.

**Comment by mseri** [comment] 2019-07-16 16:13
I guess we can close this

**Closed by mseri** 2019-07-16 16:13 UTC
Labels: enhancement
